### ISSUE TITLE
READMEの内容を改善する

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#1]
全体的な僕のイメージは以下のような感じです。

全体的にハッピーな感じを演出したい。

## 投稿してもらう内容について

* 日本のWordPressコミュニティの運営に関することを投稿してもらう
  * このリポジトリの目的をわかりやすく説明したい。
  * フォーラムやTracなどとの違いをわかりやすく説明したい。
* 立てられたIssueは明確に解決されるまでなるべく閉じない。
  * たとえば質問は回答したら閉じてしまってもいいと思う。
  * 一方でアイディアとかは実現するまで開けといたほうがいいと思う。
  * 迷ったら開けとくぐらいの感じで。将来は定例ミーティングとかのときに開いてるものをほいほい閉じていくといいかもですね。
  * あとすべてが実現されるわけではないし、実現するには投稿した御本人の協力がひつようだよということを明るく楽しく書く。

## その他

その他もろもろの報告窓口。たとえば WordPress 本体のバグなどの報告窓口やフォーラムへのリンクがあったほうがいいような気がする。

**Comment by miya0001** [comment]
* コミッターたちは個別のIssueに対して決定権がないので、コミュニティのメンバーみんなでコメントをしあってディスカッションできる空気を作れるような内容にしたい。
  * とはいえ、コミッターしかリアクションしないという状況になりそうなので、それに対する対策をなにか考えないといけない。

**Comment by miya0001** [comment]
READMEをgh-pagesにしてしまうといいかも。

**Comment by miya0001** [comment]
Watchすると通知がくることを書いたほうがいいかも。

**Comment by miminari** [comment]
諸々の設定有難うございます。
GitHubに慣れてない人はたぶんIssuesへのリンクがパッとわかりにくいと思うので、「現在投稿されているアイデアはこちら」的なリンクを貼っておいた方が良い気がします。

**Comment by 8bitodyssey** [comment]
#9 で少し文章と、フォーマットの修正を提案してみました。

**Comment by miminari** [comment]
#11 で私も試しに @8bitodyssey さんに追加で提案してみたのですが、コミッター以外はコメントの方が良いでしょうか？

**Comment by torounit** [comment]
@miminari プルリクエストも良いと思います。まだ役割もハッキリ決まってないですが、あくまでもコミッターの役割はあくまで設定などを行ったりすることなので。

#5

**Comment by miya0001** [comment]
はい、プルリクとIssueは常にウェルカムです。

**Comment by miminari** [comment]
早速お騒がせしてすみませんでした。
普段3人ぐらいのブランチも殆ど分かれないリポジトリしか扱っていないもので…勉強します。

- issue、プルリク、マージ、コンフリクト、コミッター、等のgit用語の説明

が要るかなあと思いました。READMEに入れると邪魔かも知れないので、用語集的なリンクを入れるとか。
@8bitodyssey さんが「提案」と言われていたので良いなあと思ったのですが、つい用語使っちゃいますよね。

**Comment by 8bitodyssey** [comment]
@miminari 元がプロテクトされているので、コミッターでもプルリクになります。
だから安心して投げられます(笑)

参照: #9

理解しやすい表現になるように心掛けてはいますけど、今度は熟練者が何を指している表現なのか忖度しないといけないようになるんですよねぇ。

**Comment by miminari** [comment]
まことに軽率なプルリクだったと反省しております。Slackにて3回もGitHubを推した手前、なにか手を動かさねばと焦った結果だということでどうかご容赦を。

しかし、多分、どこからならissueにするべきか、これはここにコメントしていいものなのか、どのブランチを貰ったら良いかとか、これもうプルリク送って良いのかな？とか真面目な方ほど悩まれると思うので、sandbox的なissueがあると良いかなあとか思いました。全部そこに溜まってしまう気もしますが…それか、自己紹介のようにフォーマットの決まったものを用意するとかかなあ…？

@8bitodyssey そうですよね…初めての方はこちら、的なテキストを別に用意するのが良いでしょうか。
今は運営方針を考えるフェーズなので、どうしても用語が増えてしまうと思いますが、実際のアイディア出しの段階ではそこまで出てこないとも思いますし。

**Comment by miya0001** [comment]
@miminari 全然反省していただく必要はなくて、普通に感謝しておりますのでありがとうございます。
ハードルを上げたくないのでむしろ簡単に謝らないでください。笑

> しかし、多分、どこからならissueにするべきか、これはここにコメントしていいものなのか、どのブランチを貰ったら良いかとか、これもうプルリク送って良いのかな？とか真面目な方ほど悩まれると思うので、sandbox的なissueがあると良いかなあとか思いました。全部そこに溜まってしまう気もしますが…それか、自己紹介のようにフォーマットの決まったものを用意するとか…

基本的には普通のオープンソースプロジェクトっぽいやり方でいいと思っていまして、相手が誰だかもわからないしそれがわかっていることを想定するのはおかしいですし、一般の貢献者さんが他のIssueやプルリクを全然見てないことは想定しているし、見てくれることをこちらが期待するのもおかしい、という感じで考えています。

（一方で重複があればさっさと閉じることもあるという意味でもありますが、だからといって閉じるときにネガティブに思うことはなくて閉じてしまうときでも感謝していますよ。）

あと、用語や各文書の記述内容については、プルリクエストベースで相談していきましょう。

**Comment by miya0001** [comment]
これ内容的に広すぎる感じになってきたので一度閉じますね。
