### ISSUE TITLE
Meetup Organizer Handbook の Code of Conduct テンプレートを翻訳する

### ISSUE THREAD

**Issue by ShinichiNishikawa** [jawordpressorg/ideas#10]
なににせよ、行動規範のテンプレートを翻訳しておくのは便利だと思います。

原文はこちらです。

https://make.wordpress.org/community/handbook/meetup-organizer/resources/code-of-conduct/

**Comment by torounit** [comment]
@nukaga コントリビューターデイでハンドブックの翻訳してたと思うんですが、どこにあります？

**Comment by miya0001** [comment]
これは一般論としてなんですが。

こういうやつってなかなかむずいのが、ある程度ドラフト的なものがないと「ではリポジトリを作りましょう」っていう判断をみんながしづらいんですよね。

.orgとかだと、先に個人のリポジトリでプロジェクトを始めてもらってそこでワーワー騒いでみんなに手伝ってもらう。そのあとで本家のOrganizationでフォークするなりして取り込む。という流れが多いです。

プロジェクトをこのOrganizationにばんばん増やし続けて、完成しないうちに言い出しっぺが飽きてしまうと、結果的にここのコミッターたちの負担が増え続けるというリスクがあるんです。
あとそのことが結果的に特定の人だけに権限が集中するという事態も招くのではないかと。

なので、願わくば例えば @ShinichiNishikawa さんのリポジトリとしてとりあえず始めてもらって、ある程度見えてきたらOrganizationを変更してもらうというのはどうでしょう？

その場合すべての履歴やスターの数も引き継げるし、URLもリダイレクトされます。ただし言い出しっぺがコミッターになる必要がありますが、それは逆にいえば権限の分散を合理的に安心してできるということでもあります。

**Comment by ShinichiNishikawa** [comment]
こういう一枚もののドキュメントを翻訳するとき、何かいい方法ありますか？

英語版のファイルを直接翻訳していっていいのかしら？それとも、`-ja` みたいなのを足した方がよいですか？

**Comment by nukaga** [comment]
@torounit 
現在 Googleスプレッドシートで管理しています。
https://docs.google.com/spreadsheets/d/1q_d9JIpaXPhqvNBZIdHOmFsMUFIXHd3NqRu2wLgbFXM/edit#gid=629965050
行動規範は誰もまだ訳していません。
WordSalckの #wordcamp-ja-meta チャンネルでやりとりしています。

**Comment by ShinichiNishikawa** [comment]
上記スプレッドシートから辿って、閲覧だけでいる翻訳用のシートが見つかった。

https://docs.google.com/spreadsheets/d/1mOXvaIyHya0vz5QtTtVvzSuuJakfAvdqIw1iFMW-IuA/edit#gid=0

**Comment by nukaga** [comment]
@ShinichiNishikawa 翻訳用シートのオーナーのさん（Slackアカウント j-kei ）が、リンクを知っている人すべての編集可にしてくださいました。

**Comment by nukaga** [comment]
Meetup Organizer Handbook について GitHub で翻訳すすめています。行動規範まだ誰も訳していないので、よかったらこちらご一緒しませんか？
https://github.com/jawordpressorg/community-handbook

**Comment by ixkaito** [comment]
上記リポジトリで翻訳が進んでいますのでクローズします。
