### ISSUE TITLE
コミット権の申請

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/ideas#19]
`ideas` リポジトリへのコミット権限を申請します。

## スキル

- [x] Node
- [x] PHP

## 目的

- 本リポジトリの運営をスムーズに行うため

## これまでのWordPressとの関わり

- WordPress コアコントリビューター
- WordCamp Kansai 2015 実行委員長

## WordPress.org アカウント名

[`ixkaito`](https://profiles.wordpress.org/ixkaito)

**Comment by miya0001** [comment]
招待しました。

**Comment by ixkaito** [comment]
ありがとうございます！
