### ISSUE TITLE
`ideas`チャンネルをWordSlackにつくる

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#20]
https://wpja.slack.com/archives/C02T7ML20/p1528697264000017

**Comment by ixkaito** [comment]
#ideas チャンネルに @8bitodyssey さん、 @nukaga さん、 @torounit さんを招待しました。Public にできるかどうか確認お願いします。ちなみに僕の権限ではチャンネルの削除はできないようです。

**Comment by miya0001** [comment]
仲間はずれ！ｗ

**Comment by ixkaito** [comment]
@miya0001 さん Slack の管理者じゃないからですｗ

**Comment by miya0001** [comment]
やはり仲間はずれ！ｗ

**Comment by 8bitodyssey** [comment]
mission completed!

https://wpja.slack.com/messages/CB5DVGX7X
