### ISSUE TITLE
Gutenberg のハンドブックの翻訳を GitHub ベースにするのはどうでしょうか？

### ISSUE THREAD

**Issue by miminari** [jawordpressorg/ideas#23]
今現在、スプレッドシートで管理されている [Gutenberg のハンドブック](https://wordpress.org/gutenberg/handbook/) の翻訳を GitHub ベース（進捗もマージも GitHub 上で作成）に出来たらいいなあと思っているのですがどうでしょうか？（スプレッドシートのURLをここに貼っていいか分からないので貼らずにお話します。）

日本語 « Gutenberg — WordPress
https://ja.wordpress.org/gutenberg/

こちらのページのリソース部分だけでも早く日本語化出来ないかなあと思っていまして。

単純に本家が GitHub ベースになっているので、やりやすいんじゃないかなと思ったのですがいかがでしょうか。

これまでの経緯とか仕組みとかがよく分かっていないので、何いってんだお前なお話でしたら申し訳ありませんが、ご検討のほどお願いします。

**Comment by miya0001** [comment]
ja.wordpress.org の既存のページ（要はWordPressの固定ページ）をGitHubから修正できるようにするための汎用的な仕組みは割と簡単につくれるので作っておくといいかもですね。

**Comment by miya0001** [comment]
本家のハンドブックみたいにGitHub経由でメンテしてるやつは、それとわかるように小さくボタンとか入れとくといいかもと思った。

以下のスクショは一例ですが。
![](https://www.evernote.com/l/ABUPaZcdHTBFN5Vkb5FJ1EZ0C2xH9uWwwvQB/image.png)

**Comment by miya0001** [comment]
もちろんGitHub経由ではないページとの共存はできます。

**Comment by miminari** [comment]
そう、あのボタン良いと思いました。押したら GitHub でフォークしてすぐ翻訳できる。あれのお陰でやる気になったようなものです。

**Comment by miminari** [comment]
@tekapo こんにちは！
Gutenberg のハンドブックも
https://github.com/jawordpressorg/community-handbook
に移行するのはいかがでしょうか？

**Comment by ixkaito** [comment]
@miminari https://github.com/jawordpressorg/community-handbook は一応コミュニティのハンドブック (https://make.wordpress.org/community/handbook/) をまとめたリポジトリなので、GitHub でやるにしても別リポジトリのほうがいいかも。

**Comment by miminari** [comment]
@ixkaito ご指摘ありがとうございます。そうか、すみません！混同しておりました。

**Comment by tekapo** [comment]
@miminari さん、 @nukaga さん、いいと思います。
ただ、私がちょっと手伝えそうになくって、どなたか代わりに進めてもらっていいですか?

**Comment by nukaga** [comment]
@tekapo さん、ありがとうございます。
私も今すぐにGutenberg のハンドブックに動くのは難しそうです。
リポジトリは作るので、 @miminari さん主導で動いていただくことってできますでしょうか？

**Comment by miminari** [comment]
@tekapo さん、ご賛同ありがとうございます。

@nukaga さん、ご指名ありがとうございます。翻訳ど素人ですが、私で良ければ、軽率にも承ります。

私だけでは全く力不足かと思いますが … Gutenberg のリリースが見えて来たのでなるべく早めの日本語化を目指したいです。どうぞ宜しくお願いします。

**Comment by nukaga** [comment]
ありがとうございます！

@miya0001 さん、ideas の使い方として質問なのですが、これでリポジトリを作ってすすめて良いでしょうか？

**Comment by ixkaito** [comment]
@nukaga リポジトリすでにありません？
https://github.com/jawordpressorg/gutenberg-docs

**Comment by nukaga** [comment]
@ixkaito さんありがとうございます。
このリポジトリをそのまま使ってすすめられる感じなのかな？ @miminari さん見ていただいても良いですか？

**Comment by ixkaito** [comment]
@nukaga このリポがどういう経緯で作られたのかわかりませんのでなんともです。今移動中で細かく見れませんが、僕の方でもあとで見てみます。

**Comment by nukaga** [comment]
調べました！
https://wordpress.org/gutenberg/
ページの翻訳に使ったものなので
https://wpja.slack.com/archives/C02T7MR4C/p1512543210000234

このまま使えるようであれば
https://github.com/jawordpressorg/gutenberg-docs
を使っていただく形で良さそうです。

@miminari さん、まずはプルリクエストを送っていただく形で進めてみることってできそうですか？

**Comment by miminari** [comment]
了解しました！

https://github.com/jawordpressorg/gutenberg-docs

に /doc ディレクトリを切って原文を入れ、 community に習って en ブランチを用意、
というイメージで進めますね。こうしたほうがいいよ、という事があったら教えてください。

**Comment by miminari** [comment]
そうですね、ある程度作ってみたリポジトリを提案する形がスムーズ、というのは凄くよく分かります。

この場合だと、それは全ページを翻訳したものを用意する、ということになるのでしょうか？
私は今の所1ページほど翻訳してみていますが、私のリポジトリのまま既に他の方が翻訳いただいているページなどのプルリクをいただく？ということでしょうか？？？

**Comment by miya0001** [comment]
> 私のリポジトリのまま既に他の方が翻訳いただいているページなどのプルリクをいただく？ということでしょうか？？？

そうですね。たとえば `ideas` で手伝ってくれる人を募集していただくのはウェルカムなので、ご自身でプロジェクトをまずはじめてそこにプルリクエストをもらうという感じが良いのではないかと思います。

そうすると翻訳ワークのワークフローを積極的に改善できますし、安心して失敗することもできるんじゃないかと思います。

**Comment by miminari** [comment]
了解しました！

https://github.com/miminari/gutenberg-docs

では、ご協力いただける方は、こちらにプルリクエストをいただければ幸いです。

**Comment by miminari** [comment]
…と、脊髄反射的に書いてしまいましたが、すみません、翻訳も素人な新参者が引っ張っていけるとは思えないので辞退いたします。何方か動かれる方が居たらよろしくお願いします。

**Comment by nukaga** [comment]
@miya0001 @miminari ありがとうございます。
gutenberg のドキュメント翻訳については元あったリポジトリで進めていくのでいいのかなと。
次に新しいリポジトリの作成依頼があった時にはそのように対応できたらと思いました。
また何かわからないところとか、どうしたらいい？があったら随時相談させてください。

**Comment by nukaga** [comment]
ありがとうございます。

ひとまず Gutenberg のドキュメント翻訳については元々あったリポジトリで進めていく形。

他のプロジェクトでリポジトリ作成依頼があったような時は（ケースバイケースになる部分はあるかもしれませんが）、プロジェクトリーダーのスペースにリポジトリを作成してもらって、ある程度進んでから移管という形をおすすめするという方向でいけたらと思います。

というわけで「Gutenberg のハンドブックの翻訳を GitHub ベースにするのはどうでしょうか？」isssueは解決したと思うのでcloseしますね。

ありがとうございました😊

**Comment by miya0001** [comment]
翻訳自体がまだ途中なのと、やり方自体に改善の余地があることは共通認識のようなので、開けたままにしておきますね。:blush:

**Comment by miminari** [comment]
こちらすでに以下で解決済みかと思いますので、クローズします。

https://github.com/jawordpressorg/gutenberg
