### ISSUE TITLE
ideasに各ラベルが適用されたものをSlackのチャンネルに投稿したい

### ISSUE THREAD

**Issue by musus** [jawordpressorg/ideas#27]
可能か分からないのですがラベルをSlackの各チャンネルに関連する通知を出すのはどうでしょう？

ideasの運用方法などが #ideas でおこなわれるのはいいと思うのですが #community などに関連するissueに関しては各チャンネルに通知が行くとよいかなーと思います。

**Comment by miya0001** [comment]
Related: #2 #7

**Comment by torounit** [comment]
とりあえず、現状解っていることは、Slack の Github アプリでは難しそうです。
Github での変更やissue 等を特定の channel に通知するという機能しか持っていないです。

作るなら、[Hubot](https://hubot.github.com/) とかを使えば実現できそうですが、こいつを動作させる環境の用意とメンテナンスという作業が出てきますね。

heroku とかなんですかね。

**Comment by miya0001** [comment]
サードパーティのサービスはやめましょう。そこに貢献者ロックインが入ってしまう。
TravisやGitHubなら特定の個人のアカウントへのヒモ付がゆるいのでいいのですが、特定の個人のアカウントへのヒモ付が強いとその人に必要以上に依存してしまうので。

**Comment by musus** [comment]
現状は実装を諦めるとしてクローズします!
