### ISSUE TITLE
清野をMemberにする

### ISSUE THREAD

**Issue by musus** [jawordpressorg/ideas#29]
#19 にならってコミット権の申請をします。

## スキル
- カラオケ
- PHP (少々)
- Node (一匙)

## 目的
WordPressと日本のコミュニティに貢献するために責任をもった決定をしたいから

## これまでのWordPressとの関わり
- WordPressコアコントリビューター
- WordCamp Tokyo 2014 実行委員長
- WordCamp Tokyo 2014 実行員会
- WordCamp Tokyo 2015 実行委員長
- WordCamp Tokyo 2015 実行員会
- WordCamp Tokyo 2016 実行員会
- WordCamp Tokyo 2018 実行員会
- [『Woo Each add to cart』](https://wordpress.org/plugins/woo-each-add-to-cart/) プラグイン開発者

## WP.orgアカウント
https://profiles.wordpress.org/musus

**Comment by miya0001** [comment]
一度、以下をお読みになって、なぜコミット権が必要かについて具体的な理由を明記していただけると幸いです。

https://github.com/jawordpressorg/ideas/blob/master/CONTRIBUTING.md

無駄にハードルをあげようとしているわけではないのですが、ここのコミット権を持ったからと言って各Issueに対して権限があるわけではなく（民主的にしたいからとかそういうニュアンスではなく、実際にここのコミット権とロゼッタサイト等のアクセス権等々は一切連動していない）、その一方である程度GitHubのワークフローになれている人である必要があります。

**Comment by musus** [comment]
ideasは良いと思うので主体的に参加するためにコミット権が欲しいですね。

GitHubのワークフローを熟知してませんが慣れているかどうかもちょっとわかりません。
GitHubではなく他のリポジトリサービスを使ってPMをやったりしてるのですがそれではダメでしょうか？

クローズ、プルリクのマージ、ラベルの変更等は権限がないとできないですよね？

勝手に決めてマージしていきたいとかではないのですがプロジェクトを主体的に進めていく上でコミット権が欲しいと思いました。

それではダメですか？

**Comment by miya0001** [comment]
他の方は、すでにプルリクとかのやり取りをしたことがある人ばかりで、そういうやり取りをする中で実力を証明していただいた結果権限をお願いしてるんですよね。

ぼくはその部分で無駄にハードルを上げたいとは思ってないのですがそういうアクティビティがゼロだとどうかなと。

あと、このリポジトリにコミット権なんかなくても主体的に参加できます。
例えばこんなのとかでみせていただけるといいんじゃないですかね。
https://github.com/jawordpressorg/ideas/issues/26

**Comment by musus** [comment]
ちょっとだけ理解できますが、まったくアクティビティがない人もコミット権を持っていてその理由では納得いきません。

しかし、僕なりにコミットしてからもう一回お願いしますね！

**Comment by torounit** [comment]
コミッターにならないと主体的に参加出来ないってのは違うと思います。

もし状況そういうならそれをどう直していこうかを考えたいなと。

**Comment by miya0001** [comment]
> アクティビティがない人

あとこれは誤解ですね。:blush:

**Comment by miya0001** [comment]
ラベルはこのプルリクエストで @torounit さんが誰でも提案できるようにしてくれました。
https://github.com/jawordpressorg/ideas/pull/31

安易に権限とかルールに頼るのではなくソリューションでこういうふうに解決していく感じがいいですね。 😊
