### ISSUE TITLE
WordBenchの名称の保護

### ISSUE THREAD

**Issue by maepon** [jawordpressorg/ideas#30]
WordBench.orgのサービス終了に伴って、各地のWordBenchは、WordBenchの名称の利用の停止をWordBench 運営チームにお願いされている状態です。で、現状見る限り、名称の利用の停止を各地のWordBenchは受け入れる見通しと考えられます。

このまま進むとすれば、

- WordBench.orgのサービス終了
- WordBench.orgのサイトの閉鎖
- 各地のWordBenchの終了

となると思われますが、そうなると、「WordBench」は商標など法的な裏付けがなく、実働もしていないという状態になるので、第3者によるWordBenchの名称の利用の可能性が出てきます。

これまでは一定の意識の共有のもとで利用されてきた名称が、全く意思疎通のない第3者によって利用される事態になると、最悪の場合、国内のWordPressのコミュニティやユーザーに深刻な影響が及ぶ可能性があります。
例えば、商標利用規定や100%GPLを遵守しない営利企業が、WordBenchの名称を自社の広報・マーケティングに利用するといったことです。

#28 の継続して利用するという提案が実現しなかった場合でも、上記のリスクを鑑みて何らかの方法で名称の保護をWordBench 運営チームと検討できないでしょうか？

**Comment by miya0001** [comment]
当面一番心配なのはドメイン名でしょうね。
僕も運営チームのメンバーとかではないので余計なお世話と言われそうですが。:blush:

**Comment by naokomc** [comment]
WordBench.org ドメインについては今のところ[2022年まで期限切れにはならない](http://whois.domaintools.com/wordbench.org)ようです (via @miya0001 ) ので、それである程度信頼は担保されていると思います。

三好さんによると、ドメインは手放す予定はないので、無期限自動更新にする意向だそうです。

**Comment by hikobey** [comment]
ここで発言するのは勇気がいりますが...（＾＾；
WordBenchの名称の扱いについてはハッキリさせておいた方がいいと思います（ドメインとは別に）。
例えばMeetupに登録する際の支部名称ににWordBench（地域名）が使えるのか？支部名称はWordPress Meetup（地域名）でも、開催するイベントや勉強会の名称にWordBench（地域名）が使えるのかどうかということです。使えるなら使いたいという地域もあるのではないでしょうか？
仮にいずれもWordBench（地域名）が使えない、もしくは使わないようにしようとした場合に「WordBench」自体は商標登録してないので、どこかの企業などが勝手にその名称を使ってイベントなりを運営し始めてしまうという事態が生じないかというのが懸念することです。
それこそ「WordBnench」という築き上げてきたブランド価値を損ねかねないと思います。その場合、商標登録をしないまでも、ja.wordpress.orgに、WordBenchという名称の扱いについての宣言なりなんらかの見解を表明しておくことが必要ではないかと思います。 （編集済み）

**Comment by hikobey** [comment]
ドメインについていうとwordbench.netやwordbench.jpは今でも取得可能なので、このドメインでサイトを立ち上げられてしまう可能性もあると思いまして...

**Comment by ixkaito** [comment]
商標登録をしていない以上、使用の禁止は誰にもできません。したがってこれ以上なにかを宣言することもできないと思います。したところであまり意味がないです。三好さんはみなさんに使用しないようお願いしましたが、これで十分なように思います。

名称を勝手に使われるリスクはこれまでもありましたし、法的に防ぐには商標登録するしかないが、このタイミングでする価値があるかどうかは運営チーム、はたまた WordPress ファウンデーションの判断になるでしょう。

**Comment by nukaga** [comment]
ひとまず、ドメインに関しては、今まで貼られているリンクがあるので、現状の wordbench.org については心配したのですが、それは大丈夫とのようなので、それ以上のことを求めるのは難しいかなという感想を持っています。
WordPress に関係する悪いことを考える人が WordBench を使ったら、少なくとも今 WordBench を大事にしてきた人たちは、その悪いことを考えた人は応援しないわけですし、そうやって「使うメリット」自体がなくなっていくようにも感じました。

**Comment by miya0001** [comment]
まとめると以下のような感じですかね。

* WordBench という名称自体はこれまでも悪用できたので状況はこれまでと変わらない。
* WordPress コミュニティもしくはそれに近い人や企業が WordBench という名前をあえて使うメリットはなさそう。
* `wordbench.org` ドメインは引き続き管理されるので悪用はされない。

@maepon さん、閉じてもいいかなと思いますがいかがでしょう？

**Comment by maepon** [comment]
@miya0001 活動の事実がなくなると状況は変わってくるかなとは思いますが、だとしても有効な対応手段もなさそうですね。

closeします。
