### ISSUE TITLE
WordSlackのログ置き場の移管

### ISSUE THREAD

**Issue by nukaga** [jawordpressorg/ideas#37]
現在日本語WordPress SlackのWordSlackでは、Makoさんがログを取ってくださっていました。
http://anon.step.im:8086/logs/channels

ただ新しく開設されたチャンネルのログが取得できていなかったり、メンテナンスの必要がありそうです。もともと暫定で上記を作ってくださったということもあり、複数人でのメンテナンスなど想定されていませんでした。
なのでこの機会に移管を進めてどうかという話がSlack内では出ているのですが、ログ置き場について何か案などございませんでしょうか？

https://wpja.slack.com/archives/C02RTCDCL/p1537401870000100
より @ryotsun さんの発言を引用

> 「ログを取れるようにする」という要件を満たすことだけ考えるなら、
> ・個人サーバーでいいけど複数人での管理を想定した環境を用意する
> ・とりあえずログをDBに保存する仕組みだけ作る

私の方でログ置き場にサーバーを借りて提供することも考えています。

**Comment by mako09** [comment]
Slack の仕様で古い発言が消えていくからそれを残しておけるように、ということで始めました。

「ログ」というのはあとから参照するものですし、そういった性質上 URL は可能な限り永続・不変であってほしいですよね。今回4年ぶりにようやく「暫定」を脱しそうで、ここで URL が変わってしまうのは仕方ないとしても、その後コロコロ変わらない安定した場所に落ち着いてほしいです。

**Comment by ryotsun** [comment]
slack でも少々お話しましたが、こちらにもざっくりですが書き殴ります。

### データの置き場所について
いまぱっと思いつくのはこんな感じです
#### GCP
- 無料枠があり、使い方によっては無料利用を継続できる
- クレカ登録必須なので結局個人に依存する
    - Vプリカ など利用できればある程度解消するかもしれないが、運用コスト上がりそう
- いずれにしても調査は必須

#### その他レンタルサーバー
- わぷーくらいなら格安で問題ないはず

#### 個人のサーバー
- 属人化してつらい
- クローズドになりがち
- でも、やりたいことを最速で実現できる

### 無料？有料？
正直良くわかりません…

### わたしができること
- わぷーの修理／または作り直し
    - 正直作り直したほうがいいような気もしています
        - その際は github にコードを晒す→みんなで改修／改善
    - わぷーからログ機能を切り離すのは一定あり

サーバースペースの提供は…できるけど、やらないほうがいいですね。
この歴史は繰り返さないほうがいいと思います。

**Comment by miya0001** [comment]
GCPにしろレンサバや個人のサーバーにしろ特定の個人のアカウントに依存するものはサスティナブルじゃないので、たとえばGitHubみたいにオープンソースプロジェクトは無料って明言してくれるようなものがいいかなと思いました。

Slackは一時的なものとわりきってしまうのがいいのではないかと個人的には思ってます。
大事なことは議事録として誰でも後から参照しやすいようにこのリポジトリのissueとして残すとか、P2（？）を使うとかがいいんじゃないですかね。

**Comment by mako09** [comment]
>  大事なことは議事録として誰でも後から参照しやすいようにこのリポジトリのissueとして残すとか、P2（？）を使うとかがいいんじゃないですかね。

じゃ、それを自動化する何かを考えないと。人が気にしてやらないと残らないようでは意味がないのでは。

ログなんて、ほとんど大部分は不要なものです。それでいいんです。
およそ大事なものとは、そのときには「別にとっておかなくてもいいや」と思うもので、ずいぶん後になってから「ああ、とっておけばよかった」と後悔するものです。

**Comment by nukaga** [comment]
時間がかかっててすみません。
日本のコミュニティ代理人で相談したところSlackのほうでそもそも無償提供してもらえないか、という話も出たりしています。
と、言いつつもそれも時間がかかりそうですよね。
共同のGoogleアカウントを取得してGoogleDriveに保存とかでもいいのかな、とも思いました。
https://www.google.co.jp/amp/s/motemen.hatenablog.com/entry/2015/11/gas-slack-log-spreadsheet%3famp=1

**Comment by naokomc** [comment]
[Slack for Nonprofits](https://get.slack.help/hc/en-us/articles/204368833-Slack-for-Nonprofits) というのがあったので、他のコミュニティなど使ってるのかな？と思ってコミュニティチームの Hugh に聞いてみたんですが、彼のいる南アフリカ地域も含めて各地のコミュニティで申請試してみたところもあるけど、通ったことはないとのことでした 😥

> We welcome applications from organizations that hold a valid charitable status with either the IRS (in the United States), a local tax service/charity commission, or a local TechSoup Global partner.

このへんで、切られてしまうんでしょうね…
ということで、何らかの形でログを外部に残すのに一票。

@miya0001 さんの
> 大事なことは議事録として誰でも後から参照しやすいようにこのリポジトリのissueとして残すとか、P2（？）を使うとかがいいんじゃないですかね。

というのも一理あるとは思うんですが、ある程度省略して残すことになると思うので、話の流れやあることに決定した理由を後で参照したくなったりするときに使うため、残せるのであれば残したいなと思います。

**Comment by nukaga** [comment]
考えたのですが、共有のGmailアドレスを取得してそのアカウントでコミュニティで使う共有サーバーを取得するというのが良いかと思いました。
決済等もあるので、誰かの名義にはなってしまうのですが、実質のお金はWordCampの余剰金があるところから回していただくような運用はできないかと思いました。
（WordCampの余剰金は、WordPress Foundationに寄付をするか、次回のWordCampで使うようにするか、コミュニティのために使うか、となっていたかと思います）
ちょっと時間が経ってきているので、進めたい気持ちもあります。
もし、良かったら、そういう形で進めませんか？

**Comment by miya0001** [comment]
さくらさんがCoderDojoにさくらのクラウドを100台分提供してくださっているので、お願いしてみるとかですかね。
さくらのクラウドでしたら、アカウントの管理の仕組みとかを自動化できる（CoderDojoでやってる）ので属人性を排除できるかも。

**Comment by nukaga** [comment]
おお！もし提供していただけたり、属人性を排除できるのだったらいいですね。相談しようと思うと時間かかったりしちゃうかな？
ただログ自体はそんなに重いものでもないかと思うので、安価なサーバーにしておいて、もし何かあったら乗り換えられるってのでもいいかなあとかも思います。

**Comment by ryotsun** [comment]
実は何気にログを取る仕組みを遊びがてら作っていたりします。
当初は python やら go やらで作ろうとしていましたが、他の誰でもメンテナンスをできるように…
という思いを込めて、 WordPress のプラグインという形で実装しています。
（これは完全に @naokomc さんと話したときの勢い 😅 ）

サンプルはこんな感じです↓
https://wp.4to.pics/

※ログの抽出元は個人で使っている slack チームです。

ついでにリポジトリを…↓
https://github.com/fuwalab/wp-slack-logbot

**Comment by mako09** [comment]
これはおもしろい。すばらしいです。
プラグインということは、WordPressができる程度の権限のレンタルサーバーでも大丈夫ということでしょうか。

日別チャンネル別に１記事ですか。個別の発言はいま　`<li>` ですが、それを特定して参照できるために　id　が付いていたらいいと思います。

**Comment by ryotsun** [comment]
仕様的には仰る通りです。
さらに言うと、slackにポストされる度にWordPress の記事を更新しているので
チームによってはパフォーマンスに影響が出る懸念もあります。

なので、 WordSlack の会話量的には全然捌けると思いますが、記事投稿を1日1回だけにするのもありかなとは思います。



確かに id つけた方が良さそうですね。ありがとうございます！

また、おそらく専用のテンプレートを作ることになるかな？とは思っているので、html は調整入るかもしれません。

**Comment by ryotsun** [comment]
https://github.com/jawordpressorg/ideas/issues/37#issuecomment-435096412

^ 機能的な部分は実装完了してちゃんと動くようになりました（と思っています）が、
専用のテンプレートを作る前に力尽きそうです 😄 

どなたかいい感じでシンプルな（見やすい）テンプレートを作ってくれる方いませんかー？ 🤒

**Comment by nukaga** [comment]
反応が遅くなってすみません。
@ryotsun さんありがとうございます！！すごい！！
記事投稿を1日1回、もしくはもっと頻度が低くても良いのかなと思いました。

**Comment by ryotsun** [comment]
ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!
晴れてプラグイン開発者となりました…（ぱちぱち
https://wordpress.org/plugins/wp-slack-logbot/

**Comment by nukaga** [comment]
わー！！すごい！！ありがとうございます。
サーバー問題ですが、どこか１社にWordPressコミュニティとして協力を求める形ではなく、お金を払ってレンタルサーバーを借りるのが、結局は早くて（ここまで時間はかかっていますが）、割り切れもするので健全な形なのではないかと思いました。

アカウントは共同にして、誰かの個人の持ち物にはしないようにできればと思っています。

レンタルサーバーの条件ですが下記のようなものを考えているのですが、他に追加した方が良いものとかありますでしょうか？

- コストが大きくない
- WordPressが入れられる
- 独自ドメインが使える（使うかどうかは別として）

条件に合いそうなサーバーをピックアップしようと思っています。

**Comment by mako09** [comment]
> WordPressが入れられる
「プラグインがいれられる」も必須条件ですよね。日本語公式とかにおけたらベストなのでしょうが無理だ。
公式に近いような、よく知られたサイトに相乗り、みたいなのもいいかも。

**Comment by nukaga** [comment]
確かに、「プラグインが入れられる」も必須ですね。
「公式に近いような、よく知られたサイト」というのがパッと思いつかないのですが…どこかありますかね？

**Comment by mako09** [comment]
うーん思いつきません。消滅する前の wordbench のような……。はっ! そのドメインいま持て余してるかも :p

**Comment by nukaga** [comment]
なるほど！でも、サーバー自体はAmimotoが提供してくださっていたもので、もう削除されているかと記憶しています。ドメインを使用するかは、うーん、別用途なので控えた方が良いようにも思うのと、三好さんの意向的にどうでしょうかね…。
もし、思いつけばで、他の意見も待ちつつ、レンタルサーバーのピックアップも進めてみますね。

**Comment by ryotsun** [comment]
用途が完全に別なので、ドメインの再利用などは考えないほうがいいかもしれませんね。
ぼくはレンタルサーバー事情は全然詳しくないので他の方々に任せたいと思います…
もう何年もVPSとかAWSしか触ってないので… 😅

**Comment by naokomc** [comment]
ドメインですが、レンタルサーバーのデフォルトでもらえるものを使うのもありかなと思ったんですが、引っ越しすることがないとも限らないので必須にしておいたほうがせっかくログを残すのでパーマリンクとしての継続性があって良いと思います。この用途に限るなら、直球で `wordslacklog` とかそんな感じでしょうか。

もし @ryotsun さんからの要件など特になければ、SSL + ドメイン込みのコストで選んでもいいのかなと思います。自動バックアップが残せるような機能とかも、あればいいかもしれませんが。

**Comment by ryotsun** [comment]
プラグインは特別なことはしていないので、WordPress が動く環境ならふつうに動くと思います :+1:

**Comment by nukaga** [comment]
レンタルサーバー情報をまとめてみました。各サービスもっとプランはあるのですが、WordPressがインストールできて、月額500円から1000円ぐらいのプランをまとめています。
それと昨年の日本のWordCampでサポンサーをしてくださったレンタルサーバー（サービス）の中から選んでみました。

https://docs.google.com/spreadsheets/d/1JM9nEl83_4gi-K1x5fiBhMuVqfY0enA8nKA5cCLAyo8/edit?usp=sharing

もし、追加がありましたら教えてください！

書き出してみて、なのですが。
コストだけで見るとロリポップのライトプランが安いのですが、データベースが1個なのとSSH接続ができないので、もう一つ上のプランから選んだ方が良いかなと思いました。
そうするとロリポップだとスタンダードプランになるのですが、自動バックアップが有料なので月のコストが800円から900円ほどとなり、エックスサーバーのX10プランを長期契約した場合とコストはあまり変わらないかなという感じになります。
Zenlogicは初期費用はかからないのですがSSH接続ができない、などということを考えると、さくらのレンタルサーバーのスタンダードプランか、エックスサーバーのX10プランか、ヘテムルのベーシックプランのうちから選ぶのが今回はちょうど良いのではないかなと思いました。

**Comment by nukaga** [comment]
それとドメインなのですが、汎用性のあるものにしておいて、サブドメインで wordslacklog.◯◯.org とかにしてもいいのかなあ、って思ったのですが、その方がややこしいですかね？

**Comment by nukaga** [comment]
サーバーの件ですが、なかなかコメントしにくいですよね…。
エックスサーバーのX10プランとヘテムルのベーシックプランがデータベースが作れる数が50個、70個と多かったり、容量の200Gと大きかったりするのですが、そこまで使わないかなと思うので、容量やデータベースの数は少ないものの、月のコストが安く最低限の希望の機能がある**さくらのスタンダードプラン**ではいかがでしょうか？
良かったら絵文字つけてください。**来週11月19日**までコメントを待って特に問題なさそうだったら進めたいと思います。

**Comment by ryotsun** [comment]
最近のレンサバってすごいですね。（ちょっと感動しました）
さくらのスタンダードプランで全く問題ないと思います。

もろもろありがとうございます！ 🎉

**Comment by nukaga** [comment]
皆さま反応ありがとうございますー！さくらのスタンダードプランで進めさせていただきます。
進捗みえましたら、また報告させていただきますね。

**Comment by nukaga** [comment]
この先の作業について、以下のように考えています。

・ドメインの取得
wpja.orgが取れないようなので、wpja-community.orgで取得してはどうかと思っています。

・支払いについて
一旦、私の方で立て替えて、WordCampの余剰金から支払うように相談中です。

・アカウントについて
共同アカウントのようなイメージで作業する方や必要な方にはコントロールパネルなどに入っていただけるようにします。

**Comment by ixkaito** [comment]
@nukaga wpjapan.org はどうですか？

**Comment by nukaga** [comment]
@ixkaito すみません！熱を出していてお返事遅れました。
wpjapan.org も考えたのですが、"japan"という響きがオフィシャル感を醸し出しているように感じて、community主体という意味で長くなっちゃうんですけどwpja-community.orgが良いかな、と考えました。
実は、WordSlackの方も立ち上げの時にオフィシャルではないということを明確にしてほしいという話が出てCodexの説明には、「WordPress 日本版コミュニティの非公式 Slack」と書いているというような経緯もあります。（その後他の国でも同じように言語でのSlackが立ち上がっていて、あえて非公式としなくてもいいんじゃない？というような話も出たのですが、特に結論は出ていなかったように思います）
個人的なこだわりはないので、wpjapan.org の方がいいんじゃない？となったらそれでもいいのですが、どうでしょう…？

ドメインの件、他にも意見のある方いらしたらお願いします！

**Comment by nukaga** [comment]
ドメインについても、カイトさんからもスタンプいただいて、そのほかには特になさそうなので、
https://github.com/jawordpressorg/ideas/issues/37#issuecomment-440532048
の形で進めさせていただこうと思います。設置できたらご報告しますね。

**Comment by nukaga** [comment]
ログ置き場セッティングしました！
https://wordslacklog.wpja-community.org/
@ryotsun さん、プラグイン作成と設置についてヘルプありがとうございました！

こちら未来のログのみ取得ということで、ここまでのログはSlackの機能で一旦エクスポートしています。
今まで @mako09 さんが取ってくれていたログも今までのログ置き場として引き続きリンク等はさせていただけたら助かるのですが大丈夫でしょうか？

サイトとして見やすくするとか、挙動については別にissueを立てながら改良できたらいいのかなと思っています。
WordSlackの管理権限を持っている方たちへも連絡しようと思っています。

皆さまありがとうございました！

**Comment by ryotsun** [comment]
@nukaga さんありがとうございました。
そして（ひとまず）お疲れ様でした！

運用に入るとまた色々と問題点が出てくると思いますので
協力しながらやっていければいいなぁと緩やかに思っています。

安定稼働するよう祈ってます… 🙏

**Comment by mako09** [comment]
ありがとうございます。
わぷーによる今までのログは当分の間そのままの状態で置いておきます。

**Comment by nukaga** [comment]
ありがとうございます！

運営やサイトの改善などについてはまた改めてこのideasでissueを立てるなり、 @ryotsun さんプラグインのGitHubの方で相談したりできたらいいなと思っています。
https://github.com/fuwalab/wp-slack-logbot

というわけで、こちらのissueはcloseしたいと思います。
ありがとうございました！！
