### ISSUE TITLE
ここのIssueをWordSlackの#communityと連携

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#4]
なにかコメント等があったさいに #community に投稿

**Comment by miya0001** [comment]
具体的になにをトリガーにするかも考える。

**Comment by miya0001** [comment]
WordSlackの各チャンネルとラベル名を一緒にあわせてラベルに応じて投稿できないかな。。。

#2

**Comment by miya0001** [comment]
@torounit 

これ優先順位がもっとも高いと思いました！とりあえずコメントが入るたびに #community に投稿できるように設定お願いできます？

@tekapo さんができるのかな？

僕の希望としては、

* Issueがたったとき
* Issueが閉じられた時
* コメントが投稿された時

にSlackに投稿されるとよいかと。

**Comment by torounit** [comment]
取り急ぎ、Github Slack アプリのレガシー版で、このレポジトリと、Slackの連携を行いました。

issue のステータスが変更された時、issue にコメントがついたときに #community に飛ぶように設定しいます。

Pull Request も同じようにしています。また git push されたときも同様です。
ちょっとうるさいようであれば要調整ということで。このレポジトリのWEBHOOKの設定で変更出来ます。

**Comment by ixkaito** [comment]
とりいそぎ Slack で #ideas チャンネルを作成しましたが、権限がないので public にできません。どなたかお願いします。早いとここちらに移したいです。

**Comment by nukaga** [comment]
WordSlack との連携 #ideas チャンネルへ変更してみました。（投稿テスト含む）

**Comment by miya0001** [comment]
とりあえず閉じましょうかね。
