### ISSUE TITLE
コミッターを誰にするかと役割を決める

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#5]
このリポジトリのコミッターと役割をきめる。
あとそれについてREADMEに書く。

## 大事なこと

* このリポジトリのコミッターは、あくまでもこのリポジトリの運営をスムーズに行うための設定等を目的としたもので、個別のIssueの内容に関して決定権があるわけではありません。

そのあたりを CONTRIBUTING.md に書いておくといいかも。

## 個人的に思うコミッターの条件

* Slackとの連携やときには何らかの自動化が必要かもしれないので、プログラミングができる人がいたほうがいい。
* Issueに対して決定権がないとはいえ、それぞれの課題を閉じるには投稿者本人かコミッターしかできないので、気軽にコミッターを増やすぐらいの感じが良いかなと。
  * たとえばどうにも興味がわかない Issue はどうしてもあると思うので、そういう Issue に少ない数のコミッターたちが必ずリアクションしないといけないという空気はつくりたくないです。
* 2FAは必須かも。会ったことがない人が今後入ってくる可能性があるので。ちょっと迷う。

**Comment by miya0001** [comment]
１０人ぐらいいてもいい気がするんだけど、多すぎるとセキュリティリスクあるのかな。Issue管理だけだからそれほど問題じゃない気もする。

**Comment by miya0001** [comment]
あー、あとある程度GitHubになれてることは必須かも。たとえば WordSlackの各チャンネルからひとりずつコミッターとして入るのがわかりやすい？

**Comment by torounit** [comment]
2FA(2要素認証) はコミッターには有った方が良いかなとは。それさえあればセキュリティのリスクみたいなのはかなり防げる気はするので、コミッターはガンガン増やしていけるんじゃないかと。

see.
[Providing your 2FA authentication code - User Documentation](https://help.github.com/articles/providing-your-2fa-authentication-code/)

[GitHubで二段階認証に変更する - Qiita](https://qiita.com/katsukii/items/9773e9cfea7d929fcf9c)

**Comment by miya0001** [comment]
@jawordpressorg/ideas 

コミッターの追加はCONTRIBUTING.mdに以下のようなリンクを記述して、それ経由で申請してくれた人にコミット権限を与えるというのはどうでしょう？

**Comment by ixkaito** [comment]
#21 がマージされたので閉じます。
