### ISSUE TITLE
自己紹介ができる仕組みをつくる

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#6]
Code for Philly がやってるこのやりかたいいなーと。
https://github.com/cognoma/cognoma/issues/2

自己紹介用のIssueをたてて、参加したいと思ってる人がそこに自分のスキルセットややりたいことを書いていくみたいな。

**Comment by torounit** [comment]
自己紹介して下さいっていう直球な名前なんですね。

**Comment by miya0001** [comment]
これコミッターを自己申告制にする方向でどうにかなりそうなので、自分で開いたものだし一度閉じますね。
