### ISSUE TITLE
ラベルの設定等をプルリクドリブンにしたい

### ISSUE THREAD

**Issue by miya0001** [jawordpressorg/ideas#7]
このリポジトリの設定もプルリクドリブンにして視える化したいです。

* Issue のラベルの設定（ラベルのテキストや色を定義できるやり方があるはず）
* コミッターのリスト

コミッターは[ideasというチーム](https://github.com/orgs/jawordpressorg/teams/ideas)に所属しているメンバーで、たとえばこのリポジトリにコミッターとなる人たちのアカウントのリストをコミットすることで、連携するようにしたい。

要はラベルの設定やコミッターの追加や削除が履歴として残るようにしたいです。

**Comment by torounit** [comment]
[GitHubのラベルをいい感じにセットアップするツール | Web Scratch](https://efcl.info/2017/05/17/github-label/)

@megane9988 さんが見つけてくれたこれを使ってみようかと。

このコマンドが毎回 or ラベルの色の定義ファイルが変更された時に、自動で走るようにすれば設定は出来そうですね。

**Comment by ixkaito** [comment]
できたのでクローズします。
